# Generated by Django 2.0.6 on 2018-08-07 09:27

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='', upload_to=api.models.file_upload_path)),
                ('name', models.TextField(blank=True, null=True)),
                ('hash', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('status', enumfields.fields.EnumField(default=0, enum=api.models.FileStatus, max_length=10)),
                ('created', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'db_table': 'api_file',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128)),
                ('detail', models.TextField(default='')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', enumfields.fields.EnumField(default='new', enum=api.models.CaseStatus, max_length=10)),
                ('reporter_info', models.CharField(blank=True, max_length=128, null=True)),
                ('block_height', models.IntegerField(blank=True, null=True)),
                ('block_id', models.CharField(blank=True, max_length=64, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Case')),
            ],
        ),
        migrations.CreateModel(
            name='ICO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('symbol', models.CharField(default='', max_length=128)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('platform', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('opened', models.DateTimeField(blank=True, null=True)),
                ('closed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, help_text='comma-separated string. (token_contract, smart_contract, whitepaper, facebook, medium, reddit, twitter, linkedin, slack, telegram, github, bitcointalk)', null=True, size=None)),
                ('security_category', enumfields.fields.EnumField(enum=api.models.IndicatorSecurityCategory, max_length=10)),
                ('security_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, help_text='comma-separated string. (phishing, scam, malware, hacks, exploits)', null=True, size=None)),
                ('pattern', models.CharField(max_length=256)),
                ('detail', models.TextField(blank=True, default='', null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Case')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nickname', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('permission', enumfields.fields.EnumField(default='sentinel', enum=api.models.UserPermission, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='ico',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ico_verifier', to='api.User'),
        ),
        migrations.AddField(
            model_name='case',
            name='ico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.ICO'),
        ),
        migrations.AddField(
            model_name='case',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to='api.User'),
        ),
        migrations.AddField(
            model_name='case',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reporter', to='api.User'),
        ),
        migrations.AddField(
            model_name='case',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='verifier', to='api.User'),
        ),
        migrations.AddField(
            model_name='attachedfile',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='api.Case'),
        ),
        migrations.AddField(
            model_name='attachedfile',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uploader', to='api.User'),
        ),
    ]
