# Generated by Django 4.2.7 on 2024-12-09 08:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='consumererrorlogs',
            name='api_consume_topic_ed9e7c_idx',
        ),
        migrations.AddField(
            model_name='consumererrorlogs',
            name='request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='error_logs', to='api.catvrequeststatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumererrorlogs',
            name='user_error_message',
            field=models.TextField(default=None),
        ),

        migrations.AlterField(
            model_name='consumererrorlogs',
            name='message',
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name='consumererrorlogs',
            index=models.Index(fields=['request'], name='api_consume_request_2674ff_idx'),
        ),
    ]
