# Generated by Django 2.0.6 on 2018-08-07 09:33

import api.fields
import api.models
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='block_height',
            new_name='block_num',
        ),
        migrations.RemoveField(
            model_name='case',
            name='block_id',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='tags',
        ),
        migrations.AddField(
            model_name='indicator',
            name='pattern_subtype',
            field=enumfields.fields.EnumField(blank=True, enum=api.models.IndicatorPatternSubtype, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='pattern_tree',
            field=api.fields.LtreeField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicator',
            name='pattern_type',
            field=enumfields.fields.EnumField(default='addr', enum=api.models.IndicatorPatternType, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='detail',
            field=models.TextField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator', to='api.Case'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='detail',
            field=models.TextField(blank=True, default='', max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='security_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, help_text='comma-separated string. (Phishing, Scam, Malware, Hacks, Exploits)', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=enumfields.fields.EnumField(default='sentinel', enum=api.models.UserPermission, max_length=16),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='api_case_status_89b1a3_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=django.contrib.postgres.indexes.GistIndex(fields=['pattern_tree'], name='api_indicat_pattern_f1e920_gist'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['pattern_tree'], name='api_indicat_pattern_7ef8f4_idx'),
        ),
    ]
