# Generated by Django 4.2.7 on 2025-03-13 14:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_catvcsvjobqueue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catvrequeststatus',
            name='is_legacy',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CatvNeoJobQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.JSONField(default=dict)),
                ('retries_remaining', models.IntegerField(default=3)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'api_neo_catv_job_queue',
                'indexes': [models.Index(fields=['retries_remaining'], name='api_neo_cat_retries_685c11_idx'), models.Index(fields=['created'], name='api_neo_cat_created_a1fa8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CatvNeoCSVJobQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.JSONField(default=dict)),
                ('retries_remaining', models.IntegerField(default=3)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'api_neo_csv_catv_job_queue',
                'indexes': [models.Index(fields=['retries_remaining'], name='api_neo_csv_retries_17e64b_idx'), models.Index(fields=['created'], name='api_neo_csv_created_241097_idx')],
            },
        )
    ]
