# Generated by Django 2.0.6 on 2018-08-13 06:11

import api.models
import api.storages.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ico_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ico',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=api.storages.s3.StaticS3Storage(), upload_to=api.models.image_upload_path),
        ),
    ]
