# Generated by Django 2.0.6 on 2018-08-16 02:02

import api.models
import api.storages.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180813_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ico',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=api.storages.s3.StaticS3Storage(region='ap-northeast-1'), upload_to=api.models.image_upload_path),
        ),
        migrations.AddIndex(
            model_name='attachedfile',
            index=models.Index(fields=['case'], name='api_file_case_id_4eba88_idx'),
        ),
        migrations.AddIndex(
            model_name='casehistory',
            index=models.Index(fields=['case'], name='api_casehis_case_id_8a7e27_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['case'], name='api_indicat_case_id_10ba1a_idx'),
        ),
    ]
