# Generated by Django 2.0.6 on 2018-08-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180816_0202'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['owner'], name='api_case_owner_i_e9bbc2_idx'),
        ),
    ]
