# Generated by Django 2.0.6 on 2018-08-17 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180816_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRDBCaseTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('payload', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('head_block_num', models.IntegerField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=64, null=True)),
                ('block_num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trdb_case_transaction',
            },
        ),
        migrations.RemoveIndex(
            model_name='attachedfile',
            name='api_file_case_id_4eba88_idx',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='api_case_owner_i_e9bbc2_idx',
        ),
        migrations.RemoveIndex(
            model_name='casehistory',
            name='api_casehis_case_id_8a7e27_idx',
        ),
        migrations.RemoveIndex(
            model_name='indicator',
            name='api_indicat_case_id_10ba1a_idx',
        ),
        migrations.AddField(
            model_name='trdbcasetransaction',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Case'),
        ),
        migrations.AddIndex(
            model_name='trdbcasetransaction',
            index=models.Index(fields=['case'], name='trdb_case_t_case_id_18c392_idx'),
        ),
    ]
