# Generated by Django 2.0.6 on 2018-08-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180817_0303'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attachedfile',
            index=models.Index(fields=['case'], name='api_file_case_id_4eba88_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['owner'], name='api_case_owner_i_e9bbc2_idx'),
        ),
        migrations.AddIndex(
            model_name='casehistory',
            index=models.Index(fields=['case'], name='api_casehis_case_id_8a7e27_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['case'], name='api_indicat_case_id_10ba1a_idx'),
        ),
    ]
