# Generated by Django 2.0.6 on 2018-08-17 03:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180817_0307'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trdbcasetransaction',
            name='trdb_case_t_case_id_18c392_idx',
        ),
        migrations.RemoveField(
            model_name='trdbcasetransaction',
            name='case',
        ),
        migrations.AddField(
            model_name='trdbcasetransaction',
            name='case_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddIndex(
            model_name='trdbcasetransaction',
            index=models.Index(fields=['case_uid'], name='trdb_case_t_case_ui_4110e6_idx'),
        ),
    ]
