# Generated by Django 2.0.6 on 2018-08-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180817_0330'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trdbcasetransaction',
            index=models.Index(fields=['status'], name='trdb_case_t_status_7d18f0_idx'),
        ),
    ]
