# Generated by Django 2.0.6 on 2018-08-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180817_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='UppwardRewardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=100)),
                ('gid', models.CharField(max_length=100)),
                ('cid', models.CharField(max_length=100)),
                ('referral_code', models.CharField(max_length=100)),
                ('token_addr', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'uppward_reward_info',
            },
        ),
    ]
