# Generated by Django 2.0.6 on 2018-08-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_uppwardrewardinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='uppwardrewardinfo',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
