# Generated by Django 2.0.6 on 2018-08-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_uppwardrewardinfo_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uppwardrewardinfo',
            old_name='gid',
            new_name='uid',
        ),
    ]
