# Generated by Django 2.0.6 on 2018-08-23 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180821_1338'),
    ]

    operations = [
        migrations.RunSQL("""
CREATE OR REPLACE FUNCTION add_case_invalidate_candidates()
RETURNS trigger AS $case_invalidate_candidates$
BEGIN
  IF NEW.status = 'released' AND OLD.status != 'released' THEN
    INSERT INTO case_invalidate_candidates(case_id, old_status, new_status, created, status) VALUES(OLD.id, OLD.status, NEW.status, now(), 0);
  ELSIF NEW.status = 'rejected' AND OLD.status = 'released' THEN
    INSERT INTO case_invalidate_candidates(case_id, old_status, new_status, created, status) VALUES(OLD.id, OLD.status, NEW.status, now(), 0);
  END IF;
  return NEW;
END;
$case_invalidate_candidates$ LANGUAGE plpgsql;
"""),
        migrations.RunSQL("""
CREATE TRIGGER case_invalidate_candidates_trigger
AFTER UPDATE OF status ON api_case
FOR EACH ROW
WHEN (NEW.status = 'released' OR NEW.status = 'rejected')
EXECUTE PROCEDURE add_case_invalidate_candidates();
""")
    ]
