# Generated by Django 2.0.6 on 2018-09-19 06:07

import api.models
import api.storages.s3
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180823_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseInvalidateCandidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', enumfields.fields.EnumField(enum=api.models.CaseStatus, max_length=10)),
                ('new_status', enumfields.fields.EnumField(enum=api.models.CaseStatus, max_length=10)),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'case_invalidate_candidates',
            },
        ),
        migrations.AlterField(
            model_name='ico',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=api.storages.s3.StaticS3Storage(region=None), upload_to=api.models.image_upload_path),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['created'], name='api_case_created_5df243_idx'),
        ),
        migrations.AddIndex(
            model_name='casehistory',
            index=models.Index(fields=['created'], name='api_casehis_created_5ea882_idx'),
        ),
        migrations.AddIndex(
            model_name='trdbcasetransaction',
            index=models.Index(fields=['created'], name='trdb_case_t_created_53d76c_idx'),
        ),
        migrations.AddIndex(
            model_name='uppwardrewardinfo',
            index=models.Index(fields=['created'], name='uppward_rew_created_29129c_idx'),
        ),
        migrations.AddField(
            model_name='caseinvalidatecandidates',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Case'),
        ),
        migrations.AddIndex(
            model_name='caseinvalidatecandidates',
            index=models.Index(fields=['case'], name='case_invali_case_id_8b1c84_idx'),
        ),
        migrations.AddIndex(
            model_name='caseinvalidatecandidates',
            index=models.Index(fields=['created'], name='case_invali_created_a68752_idx'),
        ),
    ]
