# Generated by Django 2.0.6 on 2018-09-19 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180919_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='casehistory',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.User'),
        ),
    ]
