# Generated by Django 2.0.6 on 2018-10-19 09:42

import api.models
import api.storages.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_casehistory_initiator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=api.storages.s3.StaticS3Storage(key='user_img/', region=None), upload_to=api.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='ico',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=api.storages.s3.StaticS3Storage(key='ico_img/', region=None), upload_to=api.models.image_upload_path),
        ),
    ]
