# Generated by Django 2.0.6 on 2018-10-24 04:30

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20181019_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('api_key', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('request_assign', models.IntegerField(blank=True, default=0, null=True)),
                ('request_current', models.IntegerField(blank=True, default=0, null=True)),
                ('type_id', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('domain', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256), blank=True, null=True, size=None)),
                ('domain_restricted', models.NullBooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('expire_datetime', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.User')),
            ],
        ),
        migrations.AddIndex(
            model_name='key',
            index=models.Index(fields=['user'], name='api_key_user_id_a1a83e_idx'),
        ),
        migrations.AddIndex(
            model_name='key',
            index=models.Index(fields=['created'], name='api_key_created_abbb17_idx'),
        ),
    ]
