# Generated by Django 2.0.6 on 2018-10-24 05:30

import api.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20181024_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='type_id',
            field=enumfields.fields.EnumField(default=1, enum=api.models.APIKeyType, max_length=10),
        ),
    ]
