# Generated by Django 2.0.6 on 2018-10-24 06:41

import api.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20181024_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='api_key',
            field=models.CharField(blank=True, default=api.models.generate_api_key, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='expire_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 6, 41, 26, 580618)),
        ),
    ]
