# Generated by Django 2.0.6 on 2018-10-24 07:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20181024_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='expire_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 7, 8, 58, 618593, tzinfo=utc)),
        ),
    ]
