# Generated by Django 2.0.6 on 2018-10-24 07:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20181024_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='expire_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 7, 45, 11, 479889, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='key',
            name='request_assign',
            field=models.IntegerField(blank=True, default=10000000, null=True),
        ),
    ]
