# Generated by Django 2.0.6 on 2018-10-25 05:18

import api.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20181024_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=enumfields.fields.EnumField(default='approved', enum=api.models.UserStatus, max_length=10),
        )
    ]
