# Generated by Django 2.0.6 on 2018-10-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20181025_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='expire_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
