# Generated by Django 2.0.6 on 2018-10-26 09:46

import api.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20181025_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=enumfields.fields.EnumField(default='approved', enum=api.models.UserStatus, max_length=16),
        ),
    ]
