# Generated by Django 2.0.6 on 2018-10-28 04:56

import api.models
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20181026_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('type', enumfields.fields.EnumField(enum=api.models.EmailSentType, max_length=20)),
            ],
        ),
    ]
