# Generated by Django 2.0.6 on 2018-10-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_emailsent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsent',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
