# Generated by Django 2.0.6 on 2018-10-29 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20181028_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
