# Generated by Django 2.0.6 on 2018-11-19 08:48

import api.models
import api.storages.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20181029_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='indicators',
            field=models.ManyToManyField(related_name='case_indicators', to='api.Indicator'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='cases',
            field=models.ManyToManyField(related_name='indicator_cases', to='api.Case'),
        ),
        migrations.AlterField(
            model_name='ico',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=api.storages.s3.StaticS3Storage(key='ico_img/', region='ap-northeast-2', resize=True), upload_to=api.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=api.storages.s3.StaticS3Storage(key='user_img/', region='ap-northeast-2', resize=True), upload_to=api.models.image_upload_path),
        ),
    ]
