# Generated by Django 2.0.6 on 2018-11-21 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20181119_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator', to='api.Case'),
        ),
    ]
