# Generated by Django 2.0.6 on 2018-11-24 16:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20181124_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ico',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ico',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ico',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ico_user', to='api.User'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='indicator',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='indicator_user', to='api.User'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['user'], name='api_indicat_user_id_8371a8_idx'),
        ),
    ]
