# Generated by Django 2.0.6 on 2020-05-28 09:07

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20200522_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_id', models.IntegerField()),
                ('points', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'api_indicator_point',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('security_category', enumfields.fields.EnumField(enum=api.models.IndicatorSecurityCategory, max_length=10)),
                ('pattern', models.CharField(max_length=256)),
                ('pattern_subtype', enumfields.fields.EnumField(blank=True, enum=api.models.IndicatorPatternSubtype, max_length=10, null=True)),
                ('pattern_type', enumfields.fields.EnumField(enum=api.models.IndicatorPatternType, max_length=32)),
                ('security_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, null=True, size=None)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('points', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=10, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelatedCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Case')),
            ],
            options={
                'db_table': 'api_related_case',
            },
        ),
        migrations.AlterField(
            model_name='indicatorextraannotation',
            name='annotation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='related_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.RelatedCase'),
        ),
    ]
