# Generated by Django 2.0.6 on 2020-05-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20200522_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorextraannotation',
            name='pattern',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
