# Generated by Django 2.0.6 on 2020-11-24 06:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_auto_20201019_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='s_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None),
        ),
    ]
