apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "portal-catv-consumer-chart.fullname" . }}
  labels:
  {{- include "portal-catv-consumer-chart.labels" . | nindent 4 }}
data:
  GCP_PROJECT_ID: {{ .Values.configMap.gcpProjectId | quote }}
  GCP_SECRET_NAME: {{ .Values.configMap.gcpSecretName | quote }}